spring.application.name=resolveit
spring.datasource.url=jdbc:mysql://localhost:3306/resolveit
spring.datasource.username=root
spring.datasource.password=@041927s$
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=PbdTGbchg1egbuNE3khLpko2hpdY58O137A9dKy4yu7
jwt.expiration=86400000
logging.level.org.springframework.security=DEBUG
logging.level.com.resolveitbackend.resolveit.security=DEBUG
spring.jackson.property-naming-strategy=SNAKE_CASE